[package]
name = "enum_traits"
version = "3.1.0"
authors = ["Lolirofle <1522957+Lolirofle@users.noreply.github.com>"]
description = "Companion traits for `enum_traits_macros`"
documentation = "https://docs.rs/enum_traits"
repository = "https://github.com/Lolirofle/enum_traits.git"
readme = "../README.md"
keywords = ["enum","trait","derive","proc-macros","macro"]
categories = ["development-tools::procedural-macro-helpers"]
license = "MIT"
edition = "2024"

[lib]
name = "enum_traits"

[dependencies]
enum_traits_macros = {path = "../macros" , optional = true}

[dev-dependencies]
enum_traits_macros = {path = "../macros"}

[features]
default = []
derive = ["enum_traits_macros"]

[package.metadata.docs.rs]
features = ["derive"]
