[package]
name = "enum_traits_gen"
version = "0.1.0"
authors = ["Lolirofle <lolipopple@hotmail.com>"]
description = "Procedural macros that adds functionality to enums by generating code and implementing traits from the crate `enum_traits`"
documentation = "https://docs.rs/enum_traits"
homepage = "https://github.com/Lolirofle/enum_traits"
repository = "https://github.com/Lolirofle/enum_traits.git"
#readme = "README.md"
keywords = ["enum","trait","derive","deriving","macro"]
license = "MIT"

[lib]
plugin = true

[dependencies]
quote = "0.3"
syn = "0.10"
