[package]
name = "enum_traits_macros"
version = "3.2.0"
authors = ["Lolirofle <1522957+Lolirofle@users.noreply.github.com>"]
description = "Procedural macros adding functionality to enums. Derives traits from the crate `enum_traits`"
documentation = "https://docs.rs/enum_traits"
repository = "https://github.com/Lolirofle/enum_traits.git"
readme = "../README.md"
keywords = ["enum","trait","derive","proc-macros","macro"]
categories = ["development-tools::procedural-macro-helpers"]
license = "MIT"
edition = "2024"

[features]
default = [
	"ends",
	"from_discriminant",
	"from_index",
	"from_variant_fields",
	"from_variant_name",
	"index",
	"is_variant_fns",
	"iter",
	"iterator",
	"len",
	"tag",
	"to_index",
	"variant_name",
	"step"
]
ends                = []
field_structs       = []
from_discriminant   = []
from_index          = []
from_variant_fields = []
from_variant_name   = []
index               = []
is_variant_fns      = []
iter                = []
iterator            = []
len                 = []
tag                 = []
to_index            = []
variant_name        = []
step                = []

[lib]
name = "enum_traits_macros"
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version="1.0" , features=["full","visit"]}
proc-macro2 = "1.0"

[dev-dependencies]
enum_traits = {path="../lib"}

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
