[package]
name = "enum_traits_macros"
version = "0.1.1"
authors = ["Lolirofle <lolipopple@hotmail.com>"]
description = "Syntax extension for the crate `enum_traits`"
#documentation = "..."
homepage = "https://github.com/Lolirofle/enum_traits"
repository = "https://github.com/Lolirofle/enum_traits.git"
#readme = "README.md"
keywords = ["enum","trait","traits"]
license = "MIT"

[lib]
plugin = true

[build-dependencies]
quasi_codegen = {version = "*",default-features=false}

[dependencies]
aster        = {version="*",default-features=false}
quasi        = {version="*",default-features=false}
quasi_macros = {version="*",default-features=false}
