[package]
name = "enum_traits_macros"
version = "6.1.0"
authors = ["Lolirofle <1522957+Lolirofle@users.noreply.github.com>"]
description = "Procedural macros adding functionality to enums. Derives traits from the crate `enum_traits`"
documentation = "https://docs.rs/enum_traits"
repository = "https://github.com/Lolirofle/enum_traits.git"
readme = "../README.md"
keywords = ["enum","trait","derive","proc-macros","macro"]
categories = ["development-tools::procedural-macro-helpers","no-std"]
license = "MIT"
edition = "2024"

[features]
default = [
	"ends",
	"field_structs",
	"from_discriminant",
	"from_index",
	"from",
	"from_variant_name",
	"index",
	"is",
	"iter",
	"iterator",
	"len",
	"tag",
	"to_index",
	"variant_name",
	"step",
	"variants_array",
	"into"
]

# Shorthand for other feature flags.
# These are not used in the codebase.
ends              = ["derive_ends"             ,"attr_ends"]
field_structs     = ["derive_field_structs"    ,"attr_field_structs"]
from_discriminant = ["derive_from_discriminant","attr_from_discriminant"]
from_index        = ["derive_from_index"       ,"attr_from_index"]
from              = ["derive_from"             ,"attr_from"]
from_variant_name = ["derive_from_variant_name","attr_from_variant_name"]
index             = ["derive_index"            ,"attr_index"]
is                = ["derive_is"               ,"attr_is"]
iter              = ["derive_iterable"         ,"attr_iterable"]
iterator          = ["derive_iterator"         ,"attr_iterator"]
len               = ["derive_len"              ,"attr_len"]
tag               = ["derive_tag"              ,"attr_tag"]
to_index          = ["derive_to_index"         ,"attr_to_index"]
variant_name      = ["derive_variant_name"     ,"attr_variant_name"]
step              = ["derive_step"             ,"attr_step"]
variants_array    = ["derive_variants_array"   ,"attr_variants_array"]
into              = ["derive_into"             ,"attr_into"]
derives = [
	"derive_ends",
	"derive_field_structs",
	"derive_from_discriminant",
	"derive_from_index",
	"derive_from",
	"derive_from_variant_name",
	"derive_index",
	"derive_is",
	"derive_iterable",
	"derive_iterator",
	"derive_len",
	"derive_tag",
	"derive_to_index",
	"derive_variant_name",
	"derive_step",
	"derive_variants_array",
	"derive_into"
]
attrs = [
	"attr_ends",
	"attr_field_structs",
	"attr_from_discriminant",
	"attr_from_index",
	"attr_from",
	"attr_from_variant_name",
	"attr_index",
	"attr_is",
	"attr_iterable",
	"attr_iterator",
	"attr_len",
	"attr_tag",
	"attr_to_index",
	"attr_variant_name",
	"attr_step",
	"attr_variants_array",
	"attr_into"
]

# Individual features flags that are used in the codebase.
derive_ends              = []
derive_field_structs     = ["syn/visit","derive_from"]
derive_from_discriminant = []
derive_from_index        = []
derive_from              = []
derive_from_variant_name = []
derive_index             = []
derive_is                = []
derive_iterable          = []
derive_iterator          = []
derive_len               = []
derive_tag               = []
derive_to_index          = []
derive_variant_name      = []
derive_step              = []
derive_variants_array    = []
derive_into              = []
attr_ends              = []
attr_field_structs     = ["syn/visit"]
attr_from_discriminant = []
attr_from_index        = ["syn/visit-mut"]
attr_from              = []
attr_from_variant_name = []
attr_index             = []
attr_is                = []
attr_iterable          = []
attr_iterator          = []
attr_len               = []
attr_tag               = []
attr_to_index          = []
attr_variant_name      = []
attr_step              = ["syn/visit-mut"]
attr_variants_array    = []
attr_into              = ["syn/visit-mut"]

[lib]
name = "enum_traits_macros"
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version="3.0" , features=["full","extra-traits"]}
proc-macro2 = "1.0"

[dev-dependencies]
enum_traits = {path="../lib"}

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
